@baseUrl = http://localhost:3333
@authToken = {{authenticateUser.response.body.token}}
@authEmail = {{authenticateUser.response.body.user.email}}
@providerId = {{listProviders.response.body.0.id}}
@authTokenProvider = {{authenticateProvider.response.body.token}}

# @name createUser
POST {{baseUrl}}/users HTTP/1.1
Content-Type: application/json

{
    "name": "Felippe Chemello",
    "email": "teste@codestack.me",
    "password": "123456"
}

###

# @name authenticateUser
POST {{baseUrl}}/sessions HTTP/1.1
Content-Type: application/json

{
    "email": "felippe@codestack.me",
    "password": "123456"
}

###

# @name authenticateProvider
POST {{baseUrl}}/sessions HTTP/1.1
Content-Type: application/json

{
    "email": "chemellofelippe@gmail.com",
    "password": "123456"
}

###

# @name forgotPassword
POST {{baseUrl}}/password/forgot HTTP/1.1
Content-Type: application/json

{
    "email": "felippechemello@gmail.com"
}

###

# @name resetPassword

POST {{baseUrl}}/password/reset HTTP/1.1
content-type: application/json

{
    "password": "123456",
    "passwordConfirmation": "1234564",
    "token": "7fa99d3f-48d2-49d8-835e-196be21442d3"
}

###

# @name showProfile

GET {{baseUrl}}/profile HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

###

# @name updateProfile

PUT {{baseUrl}}/profile HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

{
    "name": "Felippe J Chemello",
    "email": "felippechemello@gmail.com",
    "password": "7777777",
    "passwordConfirmation": "7777777",
    "oldPassword": "7777777"
}

###

# @name listProviders

GET {{baseUrl}}/providers HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

###

# @name providerMonthAvailability

GET {{baseUrl}}/providers/{{providerId}}/month-availability HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

{
    "month": "11",
    "year": "2020"
}

###

# @name providerDayAvailability

GET {{baseUrl}}/providers/{{providerId}}/day-availability HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

{
    "day": "15",
    "month": "12",
    "year": "2020"
}

###

# @name createAppointment

POST {{baseUrl}}/appointments HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

{
    "providerId": "2d1a8bdf-39a6-4f02-ad3a-ee8e4ff703ae",
    "date": "2021-01-01 10:00:00"
}

###

# @name listProviderAppointments

GET {{baseUrl}}/appointments/me HTTP/1.1
Authorization: Bearer {{authTokenProvider}}
content-type: application/json

{
    "year": "2021",
    "month": "1",
    "day": "1"
}

###

# @name updateAvatar

PATCH  {{baseUrl}}/users/avatar HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW


------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="profile.jpg"
Content-Type: image/jpeg

< ./tmp/profile.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--
###



