@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.token}}
@authEmail = {{authenticate.response.body.user.email}}
@providerId = {{listProviders.response.body.0.id}}

# @name createUser
POST {{baseUrl}}/users HTTP/1.1
Content-Type: application/json

{
    "name": "Felippe Chemello",
    "email": "chemellofelippe@gmail.com",
    "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions HTTP/1.1
Content-Type: application/json

{
    "email": "felippechemello@gmail.com",
    "password": "123456"
}

###

# @name forgotPassword
POST {{baseUrl}}/password/forgot HTTP/1.1
Content-Type: application/json

{
    "email": "felippechemello@gmail.com"
}

###

# @name resetPassword

POST {{baseUrl}}/password/reset HTTP/1.1
content-type: application/json

{
    "password": "123456",
    "token": "d02677cd-8d97-47da-9cf4-d6b20d54ba70"
}

###

# @name showProfile

GET {{baseUrl}}/profile HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

###

# @name updateProfile

PUT {{baseUrl}}/profile HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

{
    "name": "Felippe J Chemello",
    "email": "felippechemello850@outlook.com",
    "password": "7777777",
    "oldPassword": "123456"
}

###

# @name listProviders

GET {{baseUrl}}/providers HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

###

# @name providerMonthAvailability

GET {{baseUrl}}/providers/{{providerId}}/month-availability HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

{
    "month": "11",
    "year": "2020"
}

###

# @name providerDayAvailability

GET {{baseUrl}}/providers/{{providerId}}/day-availability HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

{
    "day": "15",
    "month": "12",
    "year": "2020"
}

###

# @name createAppointment

POST {{baseUrl}}/appointments HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

{
    "providerId": "6cbc1b61-cf57-44d0-b7ba-2fb09ab6fcdf",
    "date": "{{$datetime iso8601}}"
}

###


