# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v19
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          github-token: ${{ secrets.TOKEN_VERCEL_GITHUB }} #Optional
          vercel-org-id: ${{ secrets.FRONTEND_VERCEL_DEPLOY_ORGID}}  #Required
          vercel-project-id: ${{ secrets.FRONTEND_VERCEL_DEPLOY_PROJECTID}} #Required 
          working-directory: ./Conceitos/Frontend
